const SITE_CONTENT = {
  services: [
    {icon:'🚪', key:'door', title:{en:'Door Installation & Repair',es:'Instalación y reparación de puertas',uk:'Встановлення та ремонт дверей'}, text:{en:'Interior, exterior, and storm doors, frames, hardware, locks, and adjustments.',es:'Puertas interiores, exteriores y contra tormentas, marcos, herrajes, cerraduras y ajustes.',uk:'Міжкімнатні, вхідні та штормові двері, рами, фурнітура, замки й регулювання.'}},
    {icon:'🪟', key:'window', title:{en:'Window & Screen Repair',es:'Reparación de ventanas y mosquiteros',uk:'Ремонт вікон і сіток'}, text:{en:'Window hardware, storm windows, screens, trim, sealing, and minor repairs.',es:'Herrajes, contraventanas, mosquiteros, molduras, sellado y reparaciones menores.',uk:'Фурнітура, штормові вікна, сітки, оздоблення, герметизація та дрібний ремонт.'}},
    {icon:'🧱', key:'drywall', title:{en:'Drywall & Ceiling Repair',es:'Reparación de paneles de yeso y techos',uk:'Ремонт гіпсокартону та стель'}, text:{en:'Patching, damaged drywall replacement, surface preparation, and finish repairs.',es:'Parches, reemplazo de paneles dañados, preparación de superficies y acabado.',uk:'Латання, заміна пошкодженого гіпсокартону, підготовка поверхні та фінішний ремонт.'}},
    {icon:'📐', key:'trim', title:{en:'Trim & Baseboards',es:'Molduras y zócalos',uk:'Лиштви та плінтуси'}, text:{en:'Installation and repair of baseboards, casing, molding, shelving, and finish carpentry.',es:'Instalación y reparación de zócalos, molduras, estanterías y carpintería de acabado.',uk:'Встановлення та ремонт плінтусів, лиштв, молдингів, полиць і фінішних столярних елементів.'}},
    {icon:'🪑', key:'assembly', title:{en:'Furniture Assembly',es:'Montaje de muebles',uk:'Збирання меблів'}, text:{en:'Furniture, shelving, cabinets, storage systems, and ready-to-assemble products.',es:'Muebles, estanterías, gabinetes, sistemas de almacenamiento y productos para armar.',uk:'Меблі, полиці, шафи, системи зберігання та готові комплекти для складання.'}},
    {icon:'🛠️', key:'maintenance', title:{en:'General Repairs & Maintenance',es:'Reparaciones y mantenimiento general',uk:'Загальний ремонт і обслуговування'}, text:{en:'Caulking, hardware installation, minor fixture work, punch lists, and property maintenance.',es:'Sellado, instalación de herrajes, accesorios menores, listas de reparaciones y mantenimiento.',uk:'Герметизація, встановлення фурнітури, дрібні роботи з приладами, punch list та обслуговування нерухомості.'}}
  ],
  projects: [
    {image:'images/entryway-accent-wall.jpg', title:{en:'Modern Entryway Accent Wall',es:'Pared decorativa moderna en la entrada',uk:'Сучасна акцентна стіна у передпокої'}, meta:{en:'Interior finish project',es:'Proyecto de acabado interior',uk:'Проєкт внутрішнього оздоблення'}},
    {image:'images/entryway-console.jpg', title:{en:'Entryway Lighting & Finish Work',es:'Iluminación y acabados de entrada',uk:'Освітлення та оздоблення передпокою'}, meta:{en:'Lighting, trim, and interior improvements',es:'Iluminación, molduras y mejoras interiores',uk:'Освітлення, оздоблення та покращення інтер’єру'}},
    {image:'images/dining-kitchen-renovation.jpg', title:{en:'Dining & Kitchen Renovation',es:'Renovación de comedor y cocina',uk:'Ремонт їдальні та кухні'}, meta:{en:'Interior renovation and finish work',es:'Renovación interior y acabados',uk:'Ремонт інтер’єру та фінішні роботи'}}
  ],
  areas:['Parma Heights','Parma','Cleveland','Lakewood','Rocky River','Fairview Park','Brook Park','Middleburg Heights','Strongsville','North Royalton','Seven Hills','Independence','Berea','North Olmsted','Westlake','Bay Village','Avon','Avon Lake','Brecksville','Solon'],
  commercial:{en:['Rental turnover repairs','Office and retail maintenance','Punch-list completion','Door, drywall, trim, and hardware repairs','Photo updates and clear communication','Ongoing property maintenance'],es:['Reparaciones entre inquilinos','Mantenimiento de oficinas y comercios','Finalización de listas de pendientes','Reparación de puertas, drywall, molduras y herrajes','Actualizaciones con fotos y comunicación clara','Mantenimiento continuo de propiedades'],uk:['Ремонт між орендарями','Обслуговування офісів і магазинів','Виконання punch list','Ремонт дверей, гіпсокартону, оздоблення та фурнітури','Фото-звіти та чітка комунікація','Постійне обслуговування нерухомості']}
};

const TRANSLATIONS = {
 en:{nav_services:'Services',nav_projects:'Projects',nav_commercial:'Commercial',nav_about:'About',nav_estimate:'Request Estimate',hero_eyebrow:'Residential • Commercial • Property Maintenance',hero_title:'Professional handyman services in Greater Cleveland',hero_text:'Reliable repairs, installations, and property maintenance with clear communication and attention to detail.',call_now:'Call Now',text_photos:'Text Project Photos',point_1:'Honest pricing',point_2:'Quality workmanship',point_3:'Residential & commercial',quick_residential:'Residential',quick_residential_text:'Repairs, upgrades, and installations',quick_commercial:'Commercial',quick_commercial_text:'Maintenance for offices and properties',quick_rental:'Rental Properties',quick_rental_text:'Turnovers, punch lists, and repairs',services_eyebrow:'Our Services',services_title:'Practical solutions for homes and businesses',services_text:'Focused handyman services for common repairs, installations, and property improvements.',projects_eyebrow:'Featured Work',projects_title:'Real projects completed by Veritas Solution LLC',projects_text:'These photographs show actual completed work. New projects can be added without changing the page layout.',commercial_eyebrow:'Commercial & Property Maintenance',commercial_title:'Reliable support for property managers and business owners',commercial_text:'We provide maintenance and repair support for rental properties, offices, retail spaces, investors, and commercial property owners.',commercial_cta:'Discuss Property Maintenance',about_eyebrow:'About Veritas',about_title:'Professional service with straightforward communication',about_text_1:'Veritas Solution LLC provides residential and commercial handyman services throughout Greater Cleveland.',about_text_2:'We work with homeowners, landlords, property managers, investors, and businesses, with a focus on dependable workmanship and clear expectations.',areas_eyebrow:'Service Area',areas_title:'Serving Greater Cleveland',contact_eyebrow:'Request an Estimate',contact_title:'Tell us about your project',contact_text:'For a faster estimate, text the property location, a short description, and clear photos of the work.',phone_label:'Phone',text_label:'Text',send_photos:'Send project photos',footer_subtitle:'Residential & Commercial Handyman Services'},
 es:{nav_services:'Servicios',nav_projects:'Proyectos',nav_commercial:'Comercial',nav_about:'Nosotros',nav_estimate:'Solicitar presupuesto',hero_eyebrow:'Residencial • Comercial • Mantenimiento de propiedades',hero_title:'Servicios profesionales de handyman en Greater Cleveland',hero_text:'Reparaciones, instalaciones y mantenimiento confiables con comunicación clara y atención al detalle.',call_now:'Llamar ahora',text_photos:'Enviar fotos por texto',point_1:'Precios honestos',point_2:'Trabajo de calidad',point_3:'Residencial y comercial',quick_residential:'Residencial',quick_residential_text:'Reparaciones, mejoras e instalaciones',quick_commercial:'Comercial',quick_commercial_text:'Mantenimiento para oficinas y propiedades',quick_rental:'Propiedades de alquiler',quick_rental_text:'Cambios de inquilino, pendientes y reparaciones',services_eyebrow:'Nuestros servicios',services_title:'Soluciones prácticas para hogares y negocios',services_text:'Servicios de handyman para reparaciones, instalaciones y mejoras comunes.',projects_eyebrow:'Trabajos destacados',projects_title:'Proyectos reales completados por Veritas Solution LLC',projects_text:'Estas fotografías muestran trabajos reales terminados. Se pueden agregar nuevos proyectos sin cambiar el diseño.',commercial_eyebrow:'Mantenimiento comercial y de propiedades',commercial_title:'Apoyo confiable para administradores y dueños de negocios',commercial_text:'Ofrecemos mantenimiento y reparaciones para propiedades de alquiler, oficinas, comercios, inversionistas y dueños de propiedades comerciales.',commercial_cta:'Hablar sobre mantenimiento',about_eyebrow:'Sobre Veritas',about_title:'Servicio profesional con comunicación directa',about_text_1:'Veritas Solution LLC ofrece servicios residenciales y comerciales en todo Greater Cleveland.',about_text_2:'Trabajamos con propietarios, arrendadores, administradores, inversionistas y negocios, con enfoque en calidad y expectativas claras.',areas_eyebrow:'Área de servicio',areas_title:'Sirviendo Greater Cleveland',contact_eyebrow:'Solicitar presupuesto',contact_title:'Cuéntenos sobre su proyecto',contact_text:'Para una cotización más rápida, envíe la ubicación, una descripción breve y fotos claras.',phone_label:'Teléfono',text_label:'Mensaje',send_photos:'Enviar fotos del proyecto',footer_subtitle:'Servicios residenciales y comerciales'},
 uk:{nav_services:'Послуги',nav_projects:'Проєкти',nav_commercial:'Комерційні',nav_about:'Про нас',nav_estimate:'Запросити кошторис',hero_eyebrow:'Житлова • Комерційна • Обслуговування нерухомості',hero_title:'Професійні handyman-послуги у Greater Cleveland',hero_text:'Надійний ремонт, встановлення та обслуговування нерухомості з чіткою комунікацією й увагою до деталей.',call_now:'Зателефонувати',text_photos:'Надіслати фото',point_1:'Чесні ціни',point_2:'Якісна робота',point_3:'Житлові та комерційні об’єкти',quick_residential:'Житлові об’єкти',quick_residential_text:'Ремонт, покращення та встановлення',quick_commercial:'Комерційні об’єкти',quick_commercial_text:'Обслуговування офісів і нерухомості',quick_rental:'Орендна нерухомість',quick_rental_text:'Ремонт між орендарями та punch list',services_eyebrow:'Наші послуги',services_title:'Практичні рішення для будинків і бізнесу',services_text:'Handyman-послуги для типових ремонтів, встановлення та покращення нерухомості.',projects_eyebrow:'Виконані роботи',projects_title:'Реальні проєкти Veritas Solution LLC',projects_text:'Ці фотографії показують фактично виконані роботи. Нові проєкти можна додавати без зміни макета сторінки.',commercial_eyebrow:'Комерційне обслуговування нерухомості',commercial_title:'Надійна підтримка для property managers і власників бізнесу',commercial_text:'Ми виконуємо ремонт та обслуговування орендної нерухомості, офісів, магазинів, об’єктів інвесторів і комерційних власників.',commercial_cta:'Обговорити обслуговування',about_eyebrow:'Про Veritas',about_title:'Професійний сервіс і зрозуміла комунікація',about_text_1:'Veritas Solution LLC надає житлові та комерційні handyman-послуги по всьому Greater Cleveland.',about_text_2:'Ми працюємо з домовласниками, орендодавцями, property managers, інвесторами та бізнесами, з акцентом на надійність і чіткі очікування.',areas_eyebrow:'Зона обслуговування',areas_title:'Працюємо у Greater Cleveland',contact_eyebrow:'Запросити кошторис',contact_title:'Розкажіть про ваш проєкт',contact_text:'Для швидшої оцінки надішліть адресу об’єкта, короткий опис і чіткі фотографії робіт.',phone_label:'Телефон',text_label:'Повідомлення',send_photos:'Надіслати фото проєкту',footer_subtitle:'Житлові та комерційні handyman-послуги'}
};